name: Deploy no K8s DigitalOcean
on: 
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
        description: "Arquivo de Manifesto para Deploy"
      images:
        type: string
        required: true
        description: "Imagens que serão alteradas nos Manifestos"
      environment:
        type: string
        required: true
        description: "Nome do ambiente utilizado"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Obtendo Código
      uses: actions/checkout@v4.2.2
    - name: Kubeconfig
      uses: azure/k8s-set-context@v4.0.1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_MYCLUSTER }}
    - name: Create namespace if not exists
      run: |
        kubectl get namespace homolog || kubectl create namespace homolog  
        kubectl get namespace producao || kubectl create namespace producao  
    - name: Deploy Kube News
      uses: Azure/k8s-deploy@v5.0.1
      with:
        namespace: ${{ vars.APP_NAMESPACE}}
        manifests: ${{ inputs.manifests }}
        images: ${{ inputs.images }}