name: CI 
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v6.12.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          gabrieloliver001/k8s-kube-news:v1.${{ github.run_number }}
          gabrieloliver001/k8s-kube-news:latest
  
  CD-Homolog:
    needs: [CI]
    uses: gabrieloliverlima/pipeline_multi_env/.github/workflows/deploy.yml@main
    with:
      manifests: k8s/deployment.yaml
      images: gabrieloliver001/k8s-kube-news:v1.${{ github.run_number }}
      environment: homolog
    secrets: inherit

  CD-Producao:
    needs: [CI]
    uses: gabrieloliverlima/pipeline_multi_env/.github/workflows/deploy.yml@main
    with:
      manifests: k8s/deployment.yaml
      images: gabrieloliver001/k8s-kube-news:v1.${{ github.run_number }}
      environment: producao
    secrets: inherit
